### ISSUE TITLE
summary

### ISSUE THREAD

**Issue by alswhdgus10** [LikeLionYTY/memo_app#1]
# CRUD 게시판 복습(memo_app)
- application controller : 가장 먼저 요청을 받음

```ruby
root 'application#hello'
```
- rails g controller hello  home help

  - 되돌리기 : rails d

- Bootstrap 적용

  - Gemfile 에 `gem 'bootstrap-sass',gem 'jquery-rails'` 추가, bundle install

  - `assets/stylesheet` 에 custom.scss 추가

    ```css
    @import 'bootstrap-sprockets';
    @import 'bootstrap';

    body {
      padding-top: 60px;
    }

    section {
      overflow: auto;
    }

    textarea {
      resize: vertical;
    }

    .center {
      text-align: center;
    }

    .center h1 {
      margin-bottom: 10px;
    }

    #logo {
      float: left;
      margin-right: 10px;
      font-size: 1.7em;
      color: #fff;
      text-transform: uppercase;
      letter-spacing: -1px;
      padding-top: 9px;
      font-weight: bold;
      &:hover {
        color: #fff;
        text-decoration: none;
      }
    }
    ```

  - assets/javascripts/application.js에 추가

    ```javascript
    //= require jquery
    //= require bootstrap-sprockets
    ```

  - views/layout/_header.html.erb

    ```html
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "MemoApp", root_path, id: 'logo' %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "About", about_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    ```

  - views/layout/application.html.erb

    ```html
    <!DOCTYPE html>
    <html>
      <head>
        <title>*MemoApp*</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      </head>

      <body>
        <%= render 'layouts/header' %>
        <div class="container">
          <%= yield %>
        </div>
      </body>
    </html>
    ```

https://gorails.com/setup/osx/10.13-high-sierra
